[package]
name = "visualizer"
version = "0.1.0"
authors = ["Henning Dieterichs <henning.dieterichs@live.de>"]
edition = "2018"

[dependencies]
serde = "1.0.125"
serde_json = "1.0.64"
base64 = "0.13.0"