[package]
name = "demo"
version = "0.1.0"
authors = ["Henning Dieterichs <henning.dieterichs@live.de>"]
edition = "2018"
publish = false

[dependencies]
visualizer = { path = "../visualizer" }
serde = "1.0.125"
serde_json = "1.0.64"
image = "0.23.14"