[package]
name = "demo"
version = "0.1.0"
authors = ["Henning Dieterichs <henning.dieterichs@live.de>"]
edition = "2018"
publish = false

[dependencies]
image-visualizer = { path = "../image-visualizer" }
visualizer = { path = "../visualizer" }
image = "0.23.14"